#!/usr/bin/env node
/** Regenerates lib/supabase/database.types.ts from SUPABASE_DB_URL. Usage: npm run db:types */
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";

import { supabaseCommand } from "./supabase-bin.mjs";

try {
  process.loadEnvFile(".env.local");
} catch {
  // Use the environment as-is (CI).
}

const dbUrl = process.env.SUPABASE_DB_URL;
if (!dbUrl) {
  console.error("SUPABASE_DB_URL is not set. Add it to .env.local (see .env.example).");
  process.exit(1);
}

const out = "lib/supabase/database.types.ts";
const [command, args] = supabaseCommand([
  "gen",
  "types",
  "typescript",
  "--db-url",
  dbUrl,
  "--schema",
  "public",
]);
const gen = spawnSync(command, args, { encoding: "utf8", maxBuffer: 10 * 1024 * 1024 });
if (gen.status !== 0) {
  console.error(gen.stderr);
  process.exit(gen.status ?? 1);
}
writeFileSync(out, `// Generated by \`npm run db:types\`. Do not edit by hand.\n${gen.stdout}`);
spawnSync(process.execPath, ["node_modules/prettier/bin/prettier.cjs", "--write", out], {
  stdio: "inherit",
});
console.log(`Wrote ${out}`);
