// Generated by `npm run db:types`. Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      admin_settings: {
        Row: {
          auto_ack_en: string;
          auto_ack_ur: string;
          created_at: string;
          id: boolean;
          notification_recipients: string[];
          updated_at: string;
          updated_by: string | null;
        };
        ComputedFields: never;
        Insert: {
          auto_ack_en?: string;
          auto_ack_ur?: string;
          created_at?: string;
          id?: boolean;
          notification_recipients?: string[];
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          auto_ack_en?: string;
          auto_ack_ur?: string;
          created_at?: string;
          id?: boolean;
          notification_recipients?: string[];
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "admin_settings_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          created_at: string;
          email: string;
          full_name: string;
          id: string;
          is_suspended: boolean;
          locale: Database["public"]["Enums"]["locale_code"];
          phone: string | null;
          role: Database["public"]["Enums"]["user_role"];
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          email: string;
          full_name?: string;
          id: string;
          is_suspended?: boolean;
          locale?: Database["public"]["Enums"]["locale_code"];
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          full_name?: string;
          id?: string;
          is_suspended?: boolean;
          locale?: Database["public"]["Enums"]["locale_code"];
          phone?: string | null;
          role?: Database["public"]["Enums"]["user_role"];
          updated_at?: string;
        };
        Relationships: [];
      };
      queries: {
        Row: {
          answers: NonNullable<Json>;
          assignee_id: string | null;
          created_at: string;
          customer_id: string | null;
          customer_last_read_at: string | null;
          email: string;
          first_response_at: string | null;
          id: string;
          ip_hash: string | null;
          last_activity_at: string;
          last_admin_reply_at: string | null;
          locale: Database["public"]["Enums"]["locale_code"];
          message: string;
          name: string;
          phone: string | null;
          reference: string;
          search: unknown;
          source: Database["public"]["Enums"]["query_source"];
          status: Database["public"]["Enums"]["query_status"];
          subject: string;
          topic: Database["public"]["Enums"]["query_topic"];
          updated_at: string;
          utm: NonNullable<Json>;
        };
        ComputedFields: never;
        Insert: {
          answers?: NonNullable<Json>;
          assignee_id?: string | null;
          created_at?: string;
          customer_id?: string | null;
          customer_last_read_at?: string | null;
          email: string;
          first_response_at?: string | null;
          id?: string;
          ip_hash?: string | null;
          last_activity_at?: string;
          last_admin_reply_at?: string | null;
          locale?: Database["public"]["Enums"]["locale_code"];
          message: string;
          name: string;
          phone?: string | null;
          reference?: string;
          search?: never;
          source?: Database["public"]["Enums"]["query_source"];
          status?: Database["public"]["Enums"]["query_status"];
          subject: string;
          topic: Database["public"]["Enums"]["query_topic"];
          updated_at?: string;
          utm?: NonNullable<Json>;
        };
        Update: {
          answers?: NonNullable<Json>;
          assignee_id?: string | null;
          created_at?: string;
          customer_id?: string | null;
          customer_last_read_at?: string | null;
          email?: string;
          first_response_at?: string | null;
          id?: string;
          ip_hash?: string | null;
          last_activity_at?: string;
          last_admin_reply_at?: string | null;
          locale?: Database["public"]["Enums"]["locale_code"];
          message?: string;
          name?: string;
          phone?: string | null;
          reference?: string;
          search?: never;
          source?: Database["public"]["Enums"]["query_source"];
          status?: Database["public"]["Enums"]["query_status"];
          subject?: string;
          topic?: Database["public"]["Enums"]["query_topic"];
          updated_at?: string;
          utm?: NonNullable<Json>;
        };
        Relationships: [
          {
            foreignKeyName: "queries_assignee_id_fkey";
            columns: ["assignee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "queries_customer_id_fkey";
            columns: ["customer_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      query_attachments: {
        Row: {
          content_type: string;
          created_at: string;
          file_name: string;
          id: string;
          message_id: string | null;
          query_id: string;
          size_bytes: number;
          storage_path: string;
        };
        ComputedFields: never;
        Insert: {
          content_type: string;
          created_at?: string;
          file_name: string;
          id?: string;
          message_id?: string | null;
          query_id: string;
          size_bytes: number;
          storage_path: string;
        };
        Update: {
          content_type?: string;
          created_at?: string;
          file_name?: string;
          id?: string;
          message_id?: string | null;
          query_id?: string;
          size_bytes?: number;
          storage_path?: string;
        };
        Relationships: [
          {
            foreignKeyName: "query_attachments_message_id_fkey";
            columns: ["message_id"];
            isOneToOne: false;
            referencedRelation: "query_messages";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "query_attachments_query_id_fkey";
            columns: ["query_id"];
            isOneToOne: false;
            referencedRelation: "queries";
            referencedColumns: ["id"];
          },
        ];
      };
      query_events: {
        Row: {
          actor_id: string | null;
          created_at: string;
          data: NonNullable<Json>;
          id: string;
          query_id: string;
          type: Database["public"]["Enums"]["query_event_type"];
        };
        ComputedFields: never;
        Insert: {
          actor_id?: string | null;
          created_at?: string;
          data?: NonNullable<Json>;
          id?: string;
          query_id: string;
          type: Database["public"]["Enums"]["query_event_type"];
        };
        Update: {
          actor_id?: string | null;
          created_at?: string;
          data?: NonNullable<Json>;
          id?: string;
          query_id?: string;
          type?: Database["public"]["Enums"]["query_event_type"];
        };
        Relationships: [
          {
            foreignKeyName: "query_events_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "query_events_query_id_fkey";
            columns: ["query_id"];
            isOneToOne: false;
            referencedRelation: "queries";
            referencedColumns: ["id"];
          },
        ];
      };
      query_messages: {
        Row: {
          author_id: string | null;
          author_role: Database["public"]["Enums"]["message_author_role"];
          body: string;
          created_at: string;
          id: string;
          is_internal: boolean;
          query_id: string;
        };
        ComputedFields: never;
        Insert: {
          author_id?: string | null;
          author_role: Database["public"]["Enums"]["message_author_role"];
          body: string;
          created_at?: string;
          id?: string;
          is_internal?: boolean;
          query_id: string;
        };
        Update: {
          author_id?: string | null;
          author_role?: Database["public"]["Enums"]["message_author_role"];
          body?: string;
          created_at?: string;
          id?: string;
          is_internal?: boolean;
          query_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "query_messages_author_id_fkey";
            columns: ["author_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "query_messages_query_id_fkey";
            columns: ["query_id"];
            isOneToOne: false;
            referencedRelation: "queries";
            referencedColumns: ["id"];
          },
        ];
      };
      rate_limits: {
        Row: {
          created_at: string;
          id: number;
          key: string;
        };
        ComputedFields: never;
        Insert: {
          created_at?: string;
          id?: never;
          key: string;
        };
        Update: {
          created_at?: string;
          id?: never;
          key?: string;
        };
        Relationships: [];
      };
      saved_replies: {
        Row: {
          body: string;
          created_at: string;
          created_by: string | null;
          id: string;
          locale: Database["public"]["Enums"]["locale_code"] | null;
          title: string;
          updated_at: string;
        };
        ComputedFields: never;
        Insert: {
          body: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          locale?: Database["public"]["Enums"]["locale_code"] | null;
          title: string;
          updated_at?: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          created_by?: string | null;
          id?: string;
          locale?: Database["public"]["Enums"]["locale_code"] | null;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "saved_replies_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      admin_query_stats: { Args: Record<PropertyKey, never>; Returns: Json };
      confirmed_user_id: { Args: { p_email: string }; Returns: string };
      hit_rate_limit: {
        Args: { p_key: string; p_limit: number; p_window_seconds: number };
        Returns: boolean;
      };
      is_superadmin: { Args: Record<PropertyKey, never>; Returns: boolean };
      mark_query_read: { Args: { p_query_id: string }; Returns: undefined };
      next_query_reference: { Args: Record<PropertyKey, never>; Returns: string };
      promote_to_superadmin: { Args: { p_email: string }; Returns: string };
      resolve_my_query: { Args: { p_query_id: string }; Returns: boolean };
      set_customer_suspended: {
        Args: { p_suspended: boolean; p_user_id: string };
        Returns: boolean;
      };
    };
    Enums: {
      locale_code: "en" | "ur";
      message_author_role: "customer" | "superadmin" | "visitor";
      query_event_type:
        | "created"
        | "status_changed"
        | "assigned"
        | "replied"
        | "customer_replied"
        | "note_added"
        | "attachment_added"
        | "linked_to_account";
      query_source: "contact_page" | "dialog" | "pricing";
      query_status: "new" | "open" | "awaiting_customer" | "resolved" | "closed";
      query_topic: "pricing" | "demo" | "technical" | "billing" | "partnership" | "other";
      user_role: "customer" | "superadmin";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema["CompositeTypes"] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      locale_code: ["en", "ur"],
      message_author_role: ["customer", "superadmin", "visitor"],
      query_event_type: [
        "created",
        "status_changed",
        "assigned",
        "replied",
        "customer_replied",
        "note_added",
        "attachment_added",
        "linked_to_account",
      ],
      query_source: ["contact_page", "dialog", "pricing"],
      query_status: ["new", "open", "awaiting_customer", "resolved", "closed"],
      query_topic: ["pricing", "demo", "technical", "billing", "partnership", "other"],
      user_role: ["customer", "superadmin"],
    },
  },
} as const;
